-- Use database
CREATE DATABASE SajhaBhavishya;
GO
USE SajhaBhavishya;
GO


-- MEMBER table
CREATE TABLE dbo.Member(
MemberId INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(100) NOT NULL,
LastName NVARCHAR(100) NULL,
JoinedDate DATE NOT NULL,
IsActive BIT NOT NULL DEFAULT(1),
Mobile NVARCHAR(20) NULL,
Email NVARCHAR(200) NULL,
CONSTRAINT UQ_Member_Mobile UNIQUE(Mobile)
);


-- SAVINGS ACCOUNT
CREATE TABLE dbo.SavingsAccount(
SavingsAccountId INT IDENTITY(1,1) PRIMARY KEY,
MemberId INT NOT NULL UNIQUE,
Balance DECIMAL(18,2) NOT NULL DEFAULT(0),
LastUpdated DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
CONSTRAINT FK_Savings_Member FOREIGN KEY(MemberId) REFERENCES dbo.Member(MemberId) ON DELETE CASCADE
);


-- SAVINGS TRANSACTIONS
CREATE TABLE dbo.SavingsTransaction(
SavingsTransactionId BIGINT IDENTITY(1,1) PRIMARY KEY,
SavingsAccountId INT NOT NULL,
TxnDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
Type NVARCHAR(50) NOT NULL,
Amount DECIMAL(18,2) NOT NULL,
BalanceAfter DECIMAL(18,2) NOT NULL,
Remarks NVARCHAR(500) NULL,
CONSTRAINT FK_SavTxn_Account FOREIGN KEY(SavingsAccountId) REFERENCES dbo.SavingsAccount(SavingsAccountId) ON DELETE CASCADE
);

-- LOAN table
CREATE TABLE dbo.Loan(
LoanId INT IDENTITY(1,1) PRIMARY KEY,
MemberId INT NOT NULL,
Principal DECIMAL(18,2) NOT NULL,
InterestRate DECIMAL(5,4) NOT NULL DEFAULT(0.07), -- 7% annual
DisbursedDate DATE NOT NULL,
TenorMonths INT NOT NULL DEFAULT(6),
RemainingPrincipal DECIMAL(18,2) NOT NULL,
Status NVARCHAR(50) NOT NULL DEFAULT('Active'),
LastUpdated DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
CONSTRAINT FK_Loan_Member FOREIGN KEY(MemberId) REFERENCES dbo.Member(MemberId) ON DELETE CASCADE
);


-- LOAN TRANSACTIONS (disbursement, repayment, penalty)
CREATE TABLE dbo.LoanTransaction(
LoanTransactionId BIGINT IDENTITY(1,1) PRIMARY KEY,
LoanId INT NOT NULL,
TxnDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
Type NVARCHAR(50) NOT NULL,
Amount DECIMAL(18,2) NOT NULL,
BalanceAfter DECIMAL(18,2) NULL,
Remarks NVARCHAR(500) NULL,
CONSTRAINT FK_LoanTxn_Loan FOREIGN KEY(LoanId) REFERENCES dbo.Loan(LoanId) ON DELETE CASCADE
);


-- LOAN INSTALLMENTS (schedule)
CREATE TABLE dbo.LoanInstallment(
InstallmentId INT IDENTITY(1,1) PRIMARY KEY,
LoanId INT NOT NULL,
DueDate DATE NOT NULL,
PrincipalAmount DECIMAL(18,2) NOT NULL,
InterestAmount DECIMAL(18,2) NOT NULL,
PaidPrincipal DECIMAL(18,2) NOT NULL DEFAULT(0),
PaidInterest DECIMAL(18,2) NOT NULL DEFAULT(0),
Status NVARCHAR(50) NOT NULL DEFAULT('Due'),
CONSTRAINT FK_Inst_Loan FOREIGN KEY(LoanId) REFERENCES dbo.Loan(LoanId) ON DELETE CASCADE
);


-- FUND LEDGER
CREATE TABLE dbo.FundLedger(
LedgerId INT IDENTITY(1,1) PRIMARY KEY,
TxnDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
TxnType NVARCHAR(50) NOT NULL,
Amount DECIMAL(18,2) NOT NULL,
BalanceAfter DECIMAL(18,2) NOT NULL,
Remarks NVARCHAR(500) NULL
);


-- AUDIT LOG
CREATE TABLE dbo.AuditLog(
AuditId BIGINT IDENTITY(1,1) PRIMARY KEY,
EventDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
EventBy NVARCHAR(200) NULL,
EventType NVARCHAR(100) NOT NULL,
EventData NVARCHAR(MAX) NULL
);


-- Index for quick lookups
CREATE INDEX IX_Loan_Member_Status ON dbo.Loan(MemberId, Status);
CREATE INDEX IX_SavingsAccount_MemberId ON dbo.SavingsAccount(MemberId);
GO